### ISSUE TITLE
Cancel Calendly Session Button

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#105]
**Any context for feature**
<img width="205" alt="image" src="https://user-images.githubusercontent.com/56745367/234965559-a8b9c10f-5584-4527-a168-53bc2726f22c.png">
When this cancel button is clicked, the session should be deleted and Calendly should be informed so that the event is removed from a user's calendar (synced with Calendly)

**Requirements for feature**
- [ ] Add a route DELETE `sessions/<id>` that deletes the session object and also deletes the calendly event that was created with it
- [ ] You need to call Cancel event route on Calendly - https://developer.calendly.com/api-docs/afb2e9fe3a0a0-cancel-event
- [ ] Hook the `Cancel Session` button in Swift to this route that was created so that when button is pressed the event is cancelled from Calendly and our database

**Resources / tips for development**
Please sync up with Adhithya to understand how Calendly works with our backend
Ask Harsh for help on frontend side because he has been working on the Session Page

**Comment by adhi0331** [comment]
Done
