### ISSUE TITLE
Switch between View/Complete Notes for Pre-session

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#106]
**Any context for feature**
When we add notifications to our ALUM app, we need to somehow detect whether the user has completed the notes or not so as to stop notifying them. This is also important to know to display the `View pre-session notes` vs `Complete pre-session notes` on the session details page. Solution to this is we store the status of a note as saved or not in our mongoDB object for the session such that the data persists. 

**Requirements for feature**
- [x] When user saves the pre-session notes (PATCH notes), we need to mark the note as modified so that should be done by adding a sessions schema field for each type of note. 
- [x] Note this field needs to be added to the schema and the GET sessions route 
- [ ] Based on this field, you need to change between "View" or "Complete" pre-session notes so the NotesService and the GET sessions response handling would need to updated according to this. 

**Resources / tips for development**
Jenny worked on setting up the pre/post notes on frontend and Christen worked on the backend if any help is needed.

**Comment by AmanKAggarwal** [comment]
frontend change not yet made so reopening this issue

**Comment by AmanKAggarwal** [comment]
tracked by pr #103
