### ISSUE TITLE
session page should display post/pre notes based on current time & meeting time

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#107]
**Any context for feature**
When user opens up a session details page, how do we determine whether they should now work on post session form or pre-session form? It's important to understand the idea of pre and post session form so checkout the explanation below if you are not familiar. Idea is that pre should be displayed before the event whereas post should be displayed after the event. 

Pre-session form - Form that is submitted prior to a session by a mentee so that the mentee has laid out what he wants to discussion during their session. 

Post-session form - Form that is submitted by mentee & mentor (different forms) after the session is completed so that the mentee and mentor are forced to reflect on whether the session was useful and also forces them to note down what they completed

**Requirements for feature**
- [ ] Add a status to session document and GET sessions route. 
- [ ] possibly create a function that can determine the status based on start and end time
    - [ ] if current_time < start_time, status = upcoming
    - [ ] if current_time > end_time, status = completed
    - [ ] else status = ongoing
- [ ] Conditionally render buttons for View/Complete forms based on 

```
completed -> 
```
<img width="193" alt="image" src="https://user-images.githubusercontent.com/56745367/234993337-9393540d-7dfd-40a5-9863-38d332701147.png">

```
upcoming or ongoing -> 
```
<img width="184" alt="image" src="https://user-images.githubusercontent.com/56745367/234993486-13e8b46e-1dc5-4fb0-a490-d1d60ebab761.png">

**Resources / tips for development**
There can be many ways to deal with this but needs collaboration with whoever does the frontend work for this vs backend work for this. 

Reach out to Harsh/Jenny for frontend questions and Christen for backend questions.

**Comment by AmanKAggarwal** [comment]
closed by #103
