### ISSUE TITLE
Display appropriate messages when application is under review

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#110]
**Any context for feature**
When a user signs up, they are first put under review (mentor or a mentee) so until their application is approved they should only see a page that tells them their status. In our DB, these are the definitions of mentor and mentee status - 
Status: `under review` | `approved` | `paired`

**Requirements for feature**
- [ ] Enforce the status (`under review` | `approved` | `paired`) in backend on schema, routes etc. 
- [ ] Messages for `under review` and `approved` should be added as per figma
- [ ] When paired status, user should be able to see the normal screens like Home and Profile

<img width="394" alt="image" src="https://user-images.githubusercontent.com/56745367/235051991-e85a8b19-1558-4142-81d4-dc87d8f16b7e.png">

**Resources / tips for development**
Talk to Adhithya if you have any questions on the mentor/mentee schema
To test this, you shouldn't hesitate to go into our mongoDB and change the status of a mentor/mentee manually
