### ISSUE TITLE
Notes - Hook Missed Session flow with backend

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#113]
**Any context for feature**
Missed Session Question is part of the post-session forms and to persist that data we need to forward that to backend and store in DB as well. Since its part of the post session, we could store this in our post session notes document and could just be added to the PATCH notes request. 
<img width="160" alt="image" src="https://user-images.githubusercontent.com/56745367/235054559-73f11f85-4856-4f15-8118-65b13262caa4.png">

**Requirements for feature**
- [ ] Brainstorm on how to send the missed session data (send an index of the options vs sending the reason text)
- [ ] Make the edit in PATCH notes to also take into account the missed session info. If session was missed, we won't be saving any of the other data like the answer to post session questions
- [ ] Receive and store these missed session info on backend

**Resources / tips for development**

This task will require you to think about how you want to design the schema for missed session. I think we can add it to our notes document.
