### ISSUE TITLE
EPIC - Display sessions to the user

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#120]
**Context**

Sessions is one of app's prime functionality so this epic carries for both MVP and V2. Creating/Rescheduling of sessions is defined in #119 so this is only for viewing and usage of the created sessions. 

PR #103 creates SessionDetailPage **for some sessionId** and hooks up the pre/post session notes temporarily. 

**Requirements**
- [ ] All upcoming / past sessions must be listed in the sessions tab (sessions tab is in v2)
- [ ] In MVP, we need to display the SessionDetailScreen in the home tab because we only have 1 session at a time
- [ ] SessionDetailsScreen is different before and after the event 
#107
- [ ] SessionDetailsScreen should also show "View" / "Complete" notes button based on status of the note
#106 

<img width="910" alt="image" src="https://user-images.githubusercontent.com/56745367/235784785-25f6b2a4-aae4-44e2-93ff-5635371a9370.png">
