### ISSUE TITLE
EPIC - ALUM Mobile App infrastructure

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#122]
**Context**
This epic includes all tasks that doesn't particularly relate to any of our user flows but overall app working stuff. 

**Why we care?**
Well, if we don't there will be no app. It'll just be screens lol

**Requirements**
- [ ] Route all pages 
#89 
- [ ] Handle errors like internal errors and network errors cauz they WILL happen 
#112 
- [ ] After a user logs in, it is possible that they still haven't been approved into the ALUM program so handle that
#110 

** Required labels **
Make sure to manually add labels to keep our issues organized (and remove this section after)
- product:ios-app, product:admin-portal
- epics - epic:* (note - AND `epic:define` if this is an epic)
- if not epic, stack:frontend, stack:backend, stack:fullstack
