### ISSUE TITLE
EPIC - Login / Signup interface

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#123]
**Bigger picture**
If we don't have user logins and profiles, there is no way for us to connect a mentor with mentee in app. Our signup flow is purposely so lengthy because ALUM needs all that information before it can decide whether to accept a mentor/mentee into the program. 

**Details**
Once a user finishes the signup process, an application is created which needs to be approved by the admins through the admin portal (in v2) and via mongoDB (in MVP).

**Requirements**
- [X] User can login and signup as per figma
- [ ] User must be able to reset password
#49 
- [ ] When user logs in, we cannot take them to the home page unless their application is approved. States a user application can be are `under review` | `approved` | `paired` as per database schema.
#110
