### ISSUE TITLE
Home (Landing) Page for ALUM App 

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#124]
**Bigger picture**
Our app landing page needs to be something that gives instant access to things most important in the ALUM mentorship program. Those include upcoming session (v2 feature when we have multiple sessions at a time), actionable notes (designs not ready yet)

**Details**
Lot of the home page data comes from different parts of the app so if needed, we can create a route on backend specifically responsible for sending out ALL data needed on this home page so that we don't have to do multiple requests. It is not a RESTful API design but would work best for our needs.

While implementing the frontend, try to reuse as much components as possible cauz this page is a combination of other views. 

**Requirements**
- [ ] Consider and implement a route to return all information for home page
- [ ] Reuse the session card from Sessions Page
- [ ] Reuse the mentor and mentee cards
- [ ] Figure out from CurrentUser (PR #117) who is logged in

<img width="859" alt="image" src="https://user-images.githubusercontent.com/56745367/235806248-77e9799e-7653-4389-a83b-b424a1eb52ba.png">

If epic,
- product:ios-app, product:admin-portal
- epic:define
- epic:*
