### ISSUE TITLE
EPIC - Admin Portal Table Views

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#125]
**Bigger picture**
TODO

**Details**
TODO

**Requirements**
- [ ] Implement a generic table view that can be reused across the three tabs 
- [ ] Make popup components that will be used for "Application Details" + "Choose a mentor"
- [ ] Implement GET request handler for ALL mentor / mentee / sessions (missed)
- [ ] Implement PATCH request for the approval process
- [ ] Implement Missed Sessions Table + Mentor and Mentee Tables using the generic table
