### ISSUE TITLE
Epic - Mobile App notifications

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#126]
**Bigger picture**
Notifications is one of the major reason why we are making an application and not a web-app. This is because mobile notifications helps ALUM get into the everyday lives of its users which would be helpful for the mentorship program

https://www.figma.com/file/XkKYGcl4JrNqpRxqmnKJrL/ALUM?node-id=3520%3A71930&t=db2MbxOxLM7vSxYb-1

**Tech Details**
Checkout RFC - https://docs.google.com/document/d/1b4xiO5SS3PMopRNxs_QJA5U1hQCQ0lDUFjVjDdsTP2Q/edit#

Note - You cannot test out remote push notifications on a simulator so you have to run this app on your iPhone. 

**Requirements**
- [x] Research into how to do the notifications
- [ ] Setup frontend for receiving push notifications using FirebaseMessaging and APNs
- [ ] Setup a service that abstracts all the logic to send notifications using FCM on backend
- [ ] Setup flags on session document and add 2 cron jobs to send timed notifications (cron jobs should use the service)
- [ ] Send all instant notifications

<img width="358" alt="image" src="https://user-images.githubusercontent.com/56745367/235837218-4a317f1f-ab51-4cb7-a0e5-26ae46fa1f6f.png">

**Resources**
- Need to simulate the app on a physical iPhone device to test remote notifications \
    - How? https://developer.apple.com/documentation/xcode/running-your-app-in-simulator-or-on-a-device#Connect-real-devices-to-your-Mac
    - https://stackoverflow.com/questions/71618452/failed-to-prepare-device-for-development-with-xcode-13-2-1-and-ios-15-4-devic/71667372#71667372 
    - https://developer.apple.com/forums/thread/666097
- Firebase Console - https://console.firebase.google.com/u/0/project/alum-mobile-app/overview
- How to setup infra for basic remote push notifications - https://www.youtube.com/watch?v=TGOF8MqcAzY
- How to test the notifications - https://www.swiftlyrush.com/push-notifications-in-ios/
- Architecture - https://medium.com/swlh/architecting-a-scalable-notification-service-778c6fb3ac28

**Comment by AmanKAggarwal** [comment]
**Questions**
- How does refreshing work with device token?
- Should we store device token in mentor/mentee document or some other notification collection?
