### ISSUE TITLE
Integrate the buttons with profile view to wrap up this epic

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#133]
**Requirements**
- [x] Clicking "Book your session" button on profile page / session page should lead to the safari instance with calendly
- [x] Clicking "Cancel session" on session details page should make a call to DELETE /session route
- [x] Clicking "Reschedule session" on session details page should allow user to reschedule the session

**Comment by adhi0331** [comment]
Done
