### ISSUE TITLE
Use NavigationView appropropriately to make sure all back buttons work 

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#134]
**Requirements for feature**
- [x] Make sure all screens are routed properly with back button working
- [x] Make sure title is added to the header in the same line as the back button
- [x] Navigation Bar should allow customizability for things like edit profile

**Any context for feature**
N/A

**Resources / tips for development**
- Look into the usage of using separate NavigationView for each tab because each Tab will have its own back history. 
- Inside our views, there are occasions where we need to navigate between pages but sometimes that navigation should not change the "Back" button on top left. To facilitate that, we could wrap such views in its own nested NavigationView and hide the header.
