### ISSUE TITLE
Reset Password Flow

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#49]
**Requirements for feature**
- [x] Research into the 2 ways of implementing reset password flow in terms of firebase-ios-sdk
- [x] Implement the views (after research) - N/A
- [ ]  Send reset password link to user email and the reset password through that link (this will be sent when user hits "Send Verification Email")
- [ ] When forgot password is clicked, user gets navigated to a screen which takes in an email and has a "Send Reset Password Link"
- [ ] Once email is sent, navigate the user to "Success" screen 
<img width="287" alt="image" src="https://user-images.githubusercontent.com/56745367/234984100-0378dccf-05da-4a22-96f4-e5eda5ec3b56.png">

**Any context for feature**
Reset password flow deals with when user forgets their password and needs to change it. This task needs some research on how reset password works with firebase. We have two ways to go about this - 

**Decided to go with the sending reset password email because of ease in development**

1. Send reset password link to user email and the reset password through that link (this will be sent when user hits "Send Verification Email")
- CON Issue with this is we don't have control over the password strength of the new password they make because the link firebase sends only checks whether password length is more than 6 characters or not. 
- PRO very easy to implement

2. Send reset password code to user email and they enter the code in our app (current figma design)
- CON harder to implement
- PRO We have full-control on the password strength

**Resources / tips for development**
- Use firebase-ios-sdk which was already setup by #32 
Written Tutorial - https://medium.com/swift2go/firebase-authentication-using-ios-sdk-28a6a6cb9815

**Comment by AmanKAggarwal** [comment]
- Firebase does provide a reset link in email but need to figure out what the frontend for that looks like

**Comment by petabite** [comment]
Updating Firebase user password from the backend: https://firebase.google.com/docs/auth/admin/manage-users#update_a_user (Make a call to `updateUser` and pass the `password` field). You will need to implement a custom solution for the verification code email, though.
