### ISSUE TITLE
Setup local environments

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#7]
This issue is to make sure all of us are able to setup frontend and backend on their machines

Instructions for setup (frontend + backend) are provided in the README.md - https://github.com/TritonSE/ALUM-Mobile-Application/blob/main/README.md

Please let me know if you are facing any issues

### Everyone needs to setup the following things
**TODO - Copy the following two todos and make a comment with them marked as completed. (for example, see below)**
- [x] You are able to view the hello world screen preview using Xcode (image 1)
- [x] You are able to run `npm run dev` and start the server (image 2)

### Image 1
<img width="396" alt="image" src="https://user-images.githubusercontent.com/56745367/212383053-c68fbff2-8acc-4cd8-9d93-d6c298992d76.png">

### Image 2
<img width="872" alt="image" src="https://user-images.githubusercontent.com/56745367/212413795-7824d4a9-33d9-48f4-b086-e4c24a9e13dc.png">

**Comment by AmanKAggarwal** [comment]
- [ ] You are able to view the hello world screen preview using Xcode (image 1)
- [ ] You are able to run `npm run dev` and start the server (image 2)

**Comment by YashRavipati1** [comment]
- [ ] You are able to view the hello world screen preview using Xcode (image 1)
- [ ] You are able to run npm run dev and start the server (image 2)

**Comment by jennymar** [comment]
- [x] You are able to view the hello world screen preview using Xcode (image 1)
- [x] You are able to run npm run dev and start the server (image 2)

**Comment by HarshGurnani** [comment]
- [ ]  You are able to view the hello world screen preview using Xcode (image 1)
- [ ]  You are able to run npm run dev and start the server (image 2)

**Comment by sidhantrohatgi** [comment]
- [ ] You are able to view the hello world screen preview using Xcode (image 1)
- [ ] You are able to run npm run dev and start the server (image 2)

**Comment by adhi0331** [comment]
- [x] You are able to view the hello world screen preview using Xcode (image 1)
- [x] You are able to run npm run dev and start the server (image 2)

**Comment by AmanKAggarwal** [comment]
@christen03 Make sure to complete this ASAP
