### ISSUE TITLE
Session Detail Page - Create Session Detail Page & Integrate that with backend

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#88]
**Requirements for feature**
<img width="191" alt="image" src="https://user-images.githubusercontent.com/56745367/231295190-68e21388-13c9-496a-a4e1-237dbdb7ea7c.png">
- [x] Create the session details page frontend
- [x] Integrate the details page with the GET Session by ID route
- [x] Hook up the complete pre-session notes button with the completed pre-session frontend

**Any context for feature**
N/A

**Resources / tips for development**
N/A

**Comment by AmanKAggarwal** [comment]
tracked by pr #103
