### ISSUE TITLE
Use the pairing information to automatically detect mentor when POSTing a new session

### ISSUE THREAD

**Issue by AmanKAggarwal** [TritonSE/ALUM-Mobile-Application#93]
**Requirements for feature**
- [ ] Currently, the POST session route accepts mentor/mentee IDs and creates a session with that
- [ ] PR #78 streamlines the pairing mechanism so that needs to be integrated here
- [ ] POST session route should use the pairing collection to see who the requesting mentee is paired with and automatically create the session
- [ ] Only dateInfo should be passed to the route 

**Any context for feature**
N/A

**Resources / tips for development**
N/A

**Comment by AmanKAggarwal** [comment]
resolved by pr #94
